      - name: git-sync-clone
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/{{CONFIGMAP_GIT_REPO}}.git
        - name: GIT_SYNC_BRANCH
          value: {{CONFIGMAP_BRANCH}}
        - name: GIT_SYNC_ROOT
          value: /git
        - name: GIT_SYNC_DEST
          value: repo
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        image: gcr.io/google-containers/git-sync-amd64:v2.0.5
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /git
          name: airflow-dags-git
